version: "3"
    
services:
  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=TEST
      - MYSQL_USER=User
      - MYSQL_PASSWORD=12345678
      - TZ='Asia/Tokyo'
    ports:
      - 13306:3306
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24